### ISSUE TITLE
Can this tool in any way achieve e.g. workflow-dispatch(es) to actions defined in the PR head ref?

### ISSUE THREAD

**Issue by BogdanSorlea** [peter-evans/slash-command-dispatch#119]
I essentially am looking for two things (for now):
- ability to have the setup -command action as defined in the PR (not the default/main branch) - this is to, for example, be able to implement and test changes to the action without relying on a preemptive merge to master of just the -command changes, before being able to test the workflow (also, this split code approach can lead to errors - intended or not - and the situation where merges to main are added one on top of the other just to get the code where it needs to be, iteratively - because it seems there is no way to do this testing in a branch/PR, which you can then squash/clean before merging)
- I would really like to choose to have the status of the -command run posted also as an entry in the PR checks list - there can be a use-case where the same script could be run e.g. on PR open/update, but also selectively (re)run via slash-command on a PR - and in that case I would like to have the result of both cases posted in the same PR checks list; emojis are nice, but having a check status in that list - which acts as an overview - and with a direct link to see more about that action - is better

Can these things be achieved? ~I can't seem to find any info on this in the documentation.~
I now see that workflow-dispatch can be made to run with the actions in a certain branch if the `ref` argument is passed. Ok, but:
- is there a way to have it default to the PR head without having to pass it explicitly to the command (I see this as very error-prone and definitely not user friendly)
- what would then be the exact value it expects when the use-case is a PR? is it `refs/pull/10/head`, so that command would look like `/command ref=refs/pull/10/head`? because I tried that and it just says `No ref found`

**Comment by peter-evans** [comment]
Hi @BogdanSorlea

To address your first two points:
- No, this is not possible because of the way GitHub Actions works. In order to "listen" and react to comments on issues and PRs you need a workflow triggered by the `issue_comment` event. This event only triggers against the "last commit on default branch." You can see the documentation here: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#issue_comment
- This might be possible, but because of the way the GitHub's dispatch API works it could be quite challenging to achieve and not something that can be supported by this action unfortunately. The dispatch API is sort of "fire and forget" style and there is no good way to get the status of workflows triggered by dispatch. It would likely need to be a separate tool that runs in your command workflow and somehow creates checks in the PR that executed it.

For your further questions about workflow dispatch:
- No, I don't think this is possible. The context for the `issue_comment` event does not contain the `ref` of the PR is was created in, so there is no way to know. GitHub's API will default `ref` to the target repositories default branch if it's not specified.
- `ref` can be a branch, tag, or a commit SHA. See [here](https://github.com/peter-evans/slash-command-dispatch/blob/main/docs/workflow-dispatch.md#action-behaviour).

It might look "error-prone" and "not user friendly" but this action is the best version of ChatOps for GitHub Actions that I've been able to achieve within the constraints of GitHub's own APIs and the way that GitHub Actions works.

**Comment by BogdanSorlea** [comment]
your answer is very much appreciated.
I did feel there might have been github api limitations over to achiving something like this
