### ISSUE TITLE
user's permission level 'none' - moving from v1 to v3

### ISSUE THREAD

**Issue by Babu458** [peter-evans/slash-command-dispatch#189]
This action is not dispatching the commands and through this message " Command 'ok-to-apply-dev' is not configured for the user's permission level 'none' ".  We have upgraded the from v1 to v3 and the permissions didn't change.  The requester has admin access to the repo before and after the upgrade. 

current config: 
 - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        env:
          TOKEN: ***
        with:
          token: ***
          reaction-token: ***
          issue-type: pull-request
          commands: ok-to-apply-dev
          static-args: sha
          permission: write

**Comment by peter-evans** [comment]
Hi @Babu458 

Please see this issue: https://github.com/peter-evans/slash-command-dispatch/issues/128

The fix is that the PAT should be given the `org:read` scope.

**Comment by zliang-akamai** [comment]
Hi @peter-evans 
I am wondering why it needs `org:read` permission, and would it be possible to still dispatch the command when `org:read` is not granted? I think it would be nicer to let it skip the accessing repository collaborators step when it can't access it.

**Comment by peter-evans** [comment]
Hi @zliang-akamai 

Please see https://github.com/peter-evans/slash-command-dispatch/issues/128 for why `org:read` is necessary. GitHub changed the permissions model to require that scope in order to read the permissions of org users. If the action cannot determine the user's permission then it will default to `none`. So you can use the action without `org:read`, it just means that you have to set the permission of the command to `none` so that any user can execute it.
