### ISSUE TITLE
/help command

### ISSUE THREAD

**Issue by staabm** [peter-evans/slash-command-dispatch#42]
wouldn't it make sense for discoverability to have something like a `/help` command which e.g. creates a comment mentioning all available commands for the current issue/pull-request context?

**Comment by peter-evans** [comment]
I have thought about this but decided to leave the creation of a `/help` command to users because there are a few issues with building one into the action by default. The main one being that the action cannot know what arguments are available for the commands it knows about. You could solve this by adding extra config like a `help-text` input, but it just gets a bit messy and complicates the solution.

It's very easy to set one up and I might add an example to the documentation that people can copy and modify to suit their needs.

**Comment by staabm** [comment]
> It's very easy to set one up and I might add an example to the documentation that people can copy and modify to suit their needs. 

If its not feasible otherwise, documenting it sounds like a good solution.

Thx for your thoughts

**Comment by peter-evans** [comment]
I've documented the workflow for this here:
https://github.com/peter-evans/slash-command-dispatch/blob/master/docs/examples.md#help-command

**Comment by staabm** [comment]
Thank you so much - well done!
