### ISSUE TITLE
use a "error" reaction on action errors

### ISSUE THREAD

**Issue by clxmstaab** [peter-evans/slash-command-dispatch#82]
would be really cool if there was a reaction type `error` or similar, which can be used, when the github action aborts because of errors.

atm. we see a reaction for "seen" and "dispatched", but in case the action errors we won't get an update and 'wait forever' for something to appear

could by default use something like `:boom:` -> :boom:

**Comment by peter-evans** [comment]
Hi @clxmstaab 

The action itself cannot do this because once the dispatch is made there is no feedback to the action if it succeeded or not. You can, however, do this yourself. The command workflow can set a reaction on the comment to indicate that it failed.

See [this section](https://github.com/peter-evans/slash-command-dispatch#responding-to-the-comment-on-command-completion) of the readme.

Unfortunately, I don't think you can use 💥  because the reactions on comments are limited to 8 reactions. See [here](https://docs.github.com/en/rest/reference/reactions#reaction-types) for the list.

**Comment by peter-evans** [comment]
Closing this for now because I don't think there is anything I can do in the action to improve the situation here. It has to be implemented in the command workflow itself.

**Comment by clxmstaab** [comment]
side-note: github just released usability improvements to github actions which mostly render this issue useless as looking up errors in the github actions is only 1 click away since then.

https://github.blog/2020-09-23-a-better-logs-experience-with-github-actions/
